let catalog=(window.COOL_CATALOG||[]).map(p=>({...p})),orders=[],view='dashboard';
const el=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('es-DO',{style:'currency',currency:'DOP',maximumFractionDigits:0}).format(n).replace('DOP','RD$'),cloudApi=window.COOL_CLOUD||{ready:false};
function localLoad(){orders=JSON.parse(localStorage.getItem('cool-orders')||'[]');const inv=JSON.parse(localStorage.getItem('cool-inventory')||'null');if(inv)catalog.forEach(p=>p.stock=Number(inv[p.id]??p.stock))}
function setSync(text,offline=false){el('syncState').innerHTML=`<i></i> ${text}`;el('syncState').classList.toggle('offline',offline)}
function normalizeOrder(o){return {uuid:o.id,id:o.order_number,date:o.created_at,status:o.status,source:o.source,customer:{name:o.customer_name,phone:o.customer_phone,address:o.customer_address,city:o.customer_city},delivery:o.delivery,payment:o.payment,total:Number(o.total),items:(o.order_items||[]).map(x=>({id:x.product_id,name:x.product_name,price:Number(x.price),qty:x.quantity}))}}
async function cloudLoad(){const db=cloudApi.client,[productResult,orderResult]=await Promise.all([db.from('products').select('*').order('created_at'),db.from('orders').select('*,order_items(*)').order('created_at',{ascending:false})]);if(productResult.error||orderResult.error)throw(productResult.error||orderResult.error);catalog=productResult.data.map(p=>({...p,price:Number(p.price),stock:Number(p.stock)}));orders=orderResult.data.map(normalizeOrder);setSync('Sincronización en la nube');render()}
function metrics(){const today=new Date().toDateString(),todayOrders=orders.filter(o=>new Date(o.date).toDateString()===today),sales=todayOrders.filter(o=>o.status!=='Cancelado').reduce((s,o)=>s+o.total,0),pending=orders.filter(o=>o.status==='Nuevo').length,low=catalog.filter(p=>p.stock<=5).length;return [{label:'Ventas de hoy',value:money(sales),green:true},{label:'Pedidos de hoy',value:todayOrders.length},{label:'Pedidos nuevos',value:pending},{label:'Stock bajo',value:low}]}
function ordersTable(limit){const list=limit?orders.slice(0,limit):orders;return `<div class="panel"><div class="panel-head"><h2>${limit?'Pedidos recientes':'Pedidos de tienda online'}</h2><span>${list.length} registros</span></div><table class="table"><thead><tr><th>Pedido</th><th>Fecha</th><th>Cliente</th><th>Origen</th><th>Pago</th><th>Total</th><th>Estado</th><th></th></tr></thead><tbody>${list.map(o=>`<tr><td>${o.id}</td><td>${new Date(o.date).toLocaleString('es-DO')}</td><td>${o.customer.name}</td><td>${o.source}</td><td>${o.payment}</td><td><strong>${money(o.total)}</strong></td><td><span class="badge ${o.status==='Nuevo'?'new':''}">${o.status}</span></td><td><button class="action" onclick="openOrder('${o.id}')">Ver</button></td></tr>`).join('')||'<tr><td colspan="8">Todavía no hay pedidos.</td></tr>'}</tbody></table></div>`}
function render(){el('pendingCount').textContent=orders.filter(o=>o.status==='Nuevo').length;el('viewTitle').textContent={dashboard:'Resumen',orders:'Pedidos',products:'Productos',inventory:'Inventario'}[view];if(view==='dashboard')el('content').innerHTML=`<div class="metrics">${metrics().map(m=>`<article class="metric"><small>${m.label}</small><strong class="${m.green?'green':''}">${m.value}</strong></article>`).join('')}</div>${ordersTable(6)}`;if(view==='orders')el('content').innerHTML=ordersTable();if(view==='products'||view==='inventory')el('content').innerHTML=`<div class="panel"><div class="panel-head"><h2>${view==='products'?'Catálogo sincronizado':'Control de existencias'}</h2><span>${catalog.length} productos</span></div><div class="product-admin">${catalog.map(p=>`<article><img src="${p.image}" alt=""><div><h3>${p.name}</h3><p>${money(p.price)}</p><div class="stock-control"><button onclick="stock('${p.id}',-1)">−</button><b>${p.stock}</b><button onclick="stock('${p.id}',1)">+</button></div></div></article>`).join('')}</div></div>`}
async function stock(id,delta){const p=catalog.find(x=>x.id===id);if(!p)return;p.stock=Math.max(0,p.stock+delta);if(cloudApi.ready){const {error}=await cloudApi.client.from('products').update({stock:p.stock,updated_at:new Date().toISOString()}).eq('id',id);if(error){toast('No se pudo actualizar');return cloudLoad()}}else localStorage.setItem('cool-inventory',JSON.stringify(Object.fromEntries(catalog.map(x=>[x.id,x.stock]))));render();toast('Inventario actualizado')}
function openOrder(id){const o=orders.find(x=>x.id===id);if(!o)return;el('orderDetail').innerHTML=`<span class="badge new">${o.status}</span><h2>Pedido ${o.id}</h2><p><strong>${o.customer.name}</strong><br>${o.customer.phone}<br>${o.customer.address}, ${o.customer.city}</p><div class="detail-items">${o.items.map(x=>`<div><span>${x.qty} × ${x.name}</span><strong>${money(x.price*x.qty)}</strong></div>`).join('')}</div><h3>Total: ${money(o.total)}</h3><p>${o.delivery} · ${o.payment}</p><button class="action" onclick="completeOrder('${o.id}')">Marcar como confirmado</button>`;el('orderDialog').showModal()}
async function completeOrder(id){const o=orders.find(x=>x.id===id);if(!o||o.status!=='Nuevo')return;if(cloudApi.ready){const {error}=await cloudApi.client.rpc('confirm_store_order',{p_order_id:o.uuid});if(error)return toast('No se pudo confirmar');await cloudLoad()}else{o.status='Confirmado';o.items.forEach(x=>{const p=catalog.find(y=>y.id===x.id);if(p)p.stock=Math.max(0,p.stock-x.qty)});localStorage.setItem('cool-orders',JSON.stringify(orders));localStorage.setItem('cool-inventory',JSON.stringify(Object.fromEntries(catalog.map(x=>[x.id,x.stock]))));render()}el('orderDialog').close();toast('Pedido confirmado e inventario descontado')}
function toast(t){el('posToast').textContent=t;el('posToast').classList.add('show');setTimeout(()=>el('posToast').classList.remove('show'),2200)}
async function start(){if(!cloudApi.ready){el('loginScreen').classList.add('hidden');localLoad();setSync('Modo local',true);render();return}const {data}=await cloudApi.client.auth.getSession();if(data.session){el('loginScreen').classList.add('hidden');await cloudLoad();subscribe()}else{el('loginScreen').classList.remove('hidden');setSync('Acceso requerido',true)}}
function subscribe(){cloudApi.client.channel('cool-pos').on('postgres_changes',{event:'*',schema:'public',table:'orders'},()=>cloudLoad()).on('postgres_changes',{event:'*',schema:'public',table:'products'},()=>cloudLoad()).subscribe()}
el('loginForm').onsubmit=async e=>{e.preventDefault();el('loginMessage').textContent='Comprobando…';const {error}=await cloudApi.client.auth.signInWithPassword({email:el('loginEmail').value,password:el('loginPassword').value});if(error){el('loginMessage').textContent='Correo o contraseña incorrectos';return}el('loginScreen').classList.add('hidden');await cloudLoad();subscribe()};el('logoutButton').onclick=async()=>{if(cloudApi.ready)await cloudApi.client.auth.signOut();location.reload()};document.querySelectorAll('aside button[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('aside button[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;render()});start();
