const catalog=(window.COOL_CATALOG||[]).map(p=>({...p}));
const el=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('es-DO',{style:'currency',currency:'DOP',maximumFractionDigits:0}).format(n).replace('DOP','RD$');
let view='dashboard',orders=JSON.parse(localStorage.getItem('cool-orders')||'[]'),inventory=JSON.parse(localStorage.getItem('cool-inventory')||'null')||Object.fromEntries(catalog.map(p=>[p.id,p.stock]));
function saveInventory(){localStorage.setItem('cool-inventory',JSON.stringify(inventory))}
function metrics(){const today=new Date().toDateString(),todayOrders=orders.filter(o=>new Date(o.date).toDateString()===today),sales=todayOrders.reduce((s,o)=>s+o.total,0),pending=orders.filter(o=>o.status==='Nuevo').length,low=catalog.filter(p=>(inventory[p.id]??p.stock)<=5).length;return [{label:'Ventas de hoy',value:money(sales),green:true},{label:'Pedidos de hoy',value:todayOrders.length},{label:'Pedidos nuevos',value:pending},{label:'Stock bajo',value:low}]}
function ordersTable(limit){const list=limit?orders.slice(0,limit):orders;return `<div class="panel"><div class="panel-head"><h2>${limit?'Pedidos recientes':'Pedidos de tienda online'}</h2><span>${list.length} registros</span></div><table class="table"><thead><tr><th>Pedido</th><th>Fecha</th><th>Cliente</th><th>Origen</th><th>Pago</th><th>Total</th><th>Estado</th><th></th></tr></thead><tbody>${list.map(o=>`<tr><td>${o.id}</td><td>${new Date(o.date).toLocaleString('es-DO')}</td><td>${o.customer.name}</td><td>${o.source}</td><td>${o.payment}</td><td><strong>${money(o.total)}</strong></td><td><span class="badge ${o.status==='Nuevo'?'new':''}">${o.status}</span></td><td><button class="action" onclick="openOrder('${o.id}')">Ver</button></td></tr>`).join('')||'<tr><td colspan="8">Todavía no hay pedidos.</td></tr>'}</tbody></table></div>`}
function render(){el('pendingCount').textContent=orders.filter(o=>o.status==='Nuevo').length;el('viewTitle').textContent={dashboard:'Resumen',orders:'Pedidos',products:'Productos',inventory:'Inventario'}[view];if(view==='dashboard')el('content').innerHTML=`<div class="metrics">${metrics().map(m=>`<article class="metric"><small>${m.label}</small><strong class="${m.green?'green':''}">${m.value}</strong></article>`).join('')}</div>${ordersTable(6)}`;if(view==='orders')el('content').innerHTML=ordersTable();if(view==='products'||view==='inventory')el('content').innerHTML=`<div class="panel"><div class="panel-head"><h2>${view==='products'?'Catálogo sincronizado':'Control de existencias'}</h2><span>${catalog.length} productos</span></div><div class="product-admin">${catalog.map(p=>`<article><img src="${p.image}" alt=""><div><h3>${p.name}</h3><p>${money(p.price)}</p><div class="stock-control"><button onclick="stock('${p.id}',-1)">−</button><b>${inventory[p.id]??p.stock}</b><button onclick="stock('${p.id}',1)">+</button></div></div></article>`).join('')}</div></div>`}
function stock(id,delta){inventory[id]=Math.max(0,(inventory[id]||0)+delta);saveInventory();render();toast('Inventario actualizado')}
function openOrder(id){const o=orders.find(x=>x.id===id);if(!o)return;el('orderDetail').innerHTML=`<span class="badge new">${o.status}</span><h2>Pedido ${o.id}</h2><p><strong>${o.customer.name}</strong><br>${o.customer.phone}<br>${o.customer.address}, ${o.customer.city}</p><div class="detail-items">${o.items.map(x=>`<div><span>${x.qty} × ${x.name}</span><strong>${money(x.price*x.qty)}</strong></div>`).join('')}</div><h3>Total: ${money(o.total)}</h3><p>${o.delivery} · ${o.payment}</p><button class="action" onclick="completeOrder('${o.id}')">Marcar como confirmado</button>`;el('orderDialog').showModal()}
function completeOrder(id){const o=orders.find(x=>x.id===id);if(!o)return;o.status='Confirmado';o.items.forEach(x=>inventory[x.id]=Math.max(0,(inventory[x.id]||0)-x.qty));localStorage.setItem('cool-orders',JSON.stringify(orders));saveInventory();el('orderDialog').close();render();toast('Pedido confirmado e inventario descontado')}
function toast(t){el('posToast').textContent=t;el('posToast').classList.add('show');setTimeout(()=>el('posToast').classList.remove('show'),2200)}
document.querySelectorAll('aside button').forEach(b=>b.onclick=()=>{document.querySelectorAll('aside button').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;render()});window.addEventListener('storage',e=>{if(e.key==='cool-orders'){orders=JSON.parse(e.newValue||'[]');render()}});render();
