let products=(window.COOL_CATALOG||[]).map(p=>({...p}));
const money=n=>new Intl.NumberFormat('es-DO',{style:'currency',currency:'DOP',maximumFractionDigits:0}).format(n).replace('DOP','RD$');
const state={category:'Todos',query:'',cart:JSON.parse(localStorage.getItem('cool-cart')||'{}')};
const el=id=>document.getElementById(id),cloudApi=window.COOL_CLOUD||{ready:false};
const currentStock=id=>Number(products.find(x=>x.id===id)?.stock||0);
function saveCart(){localStorage.setItem('cool-cart',JSON.stringify(state.cart));renderCart()}
function categories(){return ['Todos',...new Set(products.map(p=>p.category))]}
function renderCategories(){el('categoryBar').innerHTML=categories().map(c=>`<button class="${state.category===c?'active':''}" data-category="${c}">${c}</button>`).join('');el('categoryBar').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;renderCategories();renderProducts()})}
function renderProducts(){const q=state.query.toLowerCase(),list=products.filter(p=>(state.category==='Todos'||p.category===state.category)&&(!q||`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(q)));el('resultCount').textContent=`${list.length} productos${cloudApi.ready?' · nube activa':''}`;el('productGrid').innerHTML=list.map(p=>`<article class="product-card"><div class="photo"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="stock">${p.stock>0?`${p.stock} disponibles`:'Agotado'}</span></div><div class="product-info"><small>${p.category}</small><h3>${p.name}</h3><p>${p.description}</p><div class="product-bottom"><strong>${money(p.price)}</strong><button class="add-button" data-id="${p.id}" ${p.stock<1?'disabled':''}>+ Agregar</button></div></div></article>`).join('')||'<p class="empty">No encontramos productos con esa búsqueda.</p>';el('productGrid').querySelectorAll('.add-button').forEach(b=>b.onclick=()=>addToCart(b.dataset.id))}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p||p.stock<1)return;state.cart[id]=Math.min((state.cart[id]||0)+1,p.stock);saveCart();showToast(`${p.name} agregado`)}
function changeQty(id,delta){state.cart[id]=Math.max(0,Math.min((state.cart[id]||0)+delta,currentStock(id)));if(!state.cart[id])delete state.cart[id];saveCart()}
function cartTotal(){return Object.entries(state.cart).reduce((sum,[id,q])=>sum+(products.find(p=>p.id===id)?.price||0)*q,0)}
function renderCart(){const entries=Object.entries(state.cart).filter(([id])=>products.some(p=>p.id===id));el('cartCount').textContent=entries.reduce((s,[,q])=>s+q,0);el('cartItems').innerHTML=entries.length?entries.map(([id,q])=>{const p=products.find(x=>x.id===id);return `<article class="cart-item"><img src="${p.image}" alt=""><div><h4>${p.name}</h4><small>${money(p.price*q)}</small></div><div class="qty"><button data-id="${id}" data-delta="-1">−</button><b>${q}</b><button data-id="${id}" data-delta="1">+</button></div></article>`}).join(''):'<div class="empty">Tu carrito está vacío.<br>Agrega productos para comenzar.</div>';el('cartSubtotal').textContent=money(cartTotal());el('cartItems').querySelectorAll('.qty button').forEach(b=>b.onclick=()=>changeQty(b.dataset.id,Number(b.dataset.delta)))}
function toggleCart(open){el('cartDrawer').classList.toggle('open',open);el('overlay').classList.toggle('show',open);el('cartDrawer').setAttribute('aria-hidden',String(!open))}
function showToast(message){el('toast').textContent=message;el('toast').classList.add('show');setTimeout(()=>el('toast').classList.remove('show'),2500)}
function paymentText(value){return value==='Tarjeta'?'Te enviaremos un enlace seguro cuando la pasarela bancaria esté habilitada.':value==='Contra entrega'?'Confirmaremos cobertura, entrega y monto antes de despachar.':value==='WhatsApp'?'El pedido se abrirá en WhatsApp para confirmar disponibilidad y entrega.':'Recibirás los datos bancarios y la confirmación del pedido por WhatsApp.'}
function orderFromForm(form){const data=Object.fromEntries(new FormData(form)),items=Object.entries(state.cart).map(([id,q])=>{const p=products.find(x=>x.id===id);return {id,name:p.name,price:Number(p.price),qty:q}});return {id:'CS-'+Date.now().toString().slice(-8),date:new Date().toISOString(),status:'Nuevo',source:'Tienda online',customer:{name:data.name,phone:data.phone,address:data.address,city:data.city},delivery:data.delivery,payment:data.payment,items,total:cartTotal()}}
async function saveOrder(order){if(!cloudApi.ready){const orders=JSON.parse(localStorage.getItem('cool-orders')||'[]');orders.unshift(order);localStorage.setItem('cool-orders',JSON.stringify(orders));return order}const {data,error}=await cloudApi.client.rpc('create_store_order',{p_customer_name:order.customer.name,p_customer_phone:order.customer.phone,p_customer_address:order.customer.address,p_customer_city:order.customer.city,p_delivery:order.delivery,p_payment:order.payment,p_items:order.items.map(x=>({product_id:x.id,quantity:x.qty}))});if(error)throw error;order.id=data;return order}
function sendOrder(order){const items=order.items.map(x=>`• ${x.qty} x ${x.name} — ${money(x.price*x.qty)}`).join('\n');const message=`*NUEVO PEDIDO ${order.id}*\n\n${items}\n\n*Total:* ${money(order.total)}\n*Cliente:* ${order.customer.name}\n*Teléfono:* ${order.customer.phone}\n*Entrega:* ${order.delivery}\n*Dirección:* ${order.customer.address}, ${order.customer.city}\n*Pago:* ${order.payment}`;window.open(`https://wa.me/18095095225?text=${encodeURIComponent(message)}`,'_blank')}
async function loadProducts(){if(!cloudApi.ready)return;const {data,error}=await cloudApi.client.from('products').select('id,name,category,description,image,price,stock').eq('active',true).order('created_at');if(!error&&data?.length){products=data.map(p=>({...p,price:Number(p.price),stock:Number(p.stock)}));renderCategories();renderProducts();renderCart()}}
el('searchInput').oninput=e=>{state.query=e.target.value;renderProducts()};el('cartButton').onclick=()=>toggleCart(true);el('closeCart').onclick=()=>toggleCart(false);el('overlay').onclick=()=>toggleCart(false);el('checkoutButton').onclick=()=>{if(!Object.keys(state.cart).length)return showToast('Tu carrito está vacío');toggleCart(false);el('checkoutDialog').showModal()};el('closeCheckout').onclick=()=>el('checkoutDialog').close();document.querySelectorAll('[name="payment"]').forEach(r=>r.onchange=()=>el('paymentNote').textContent=paymentText(r.value));el('checkoutForm').onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('[type="submit"]'),order=orderFromForm(e.currentTarget);button.disabled=true;button.textContent='Guardando pedido…';try{await saveOrder(order);sendOrder(order);state.cart={};saveCart();e.currentTarget.reset();el('checkoutDialog').close();showToast(`Pedido ${order.id} creado`)}catch(error){console.error(error);showToast('No se pudo guardar. Intenta nuevamente.')}finally{button.disabled=false;button.textContent='Crear pedido'}};
renderCategories();renderProducts();renderCart();loadProducts();
