const products=window.COOL_CATALOG||[];
const money=n=>new Intl.NumberFormat('es-DO',{style:'currency',currency:'DOP',maximumFractionDigits:0}).format(n).replace('DOP','RD$');
const state={category:'Todos',query:'',cart:JSON.parse(localStorage.getItem('cool-cart')||'{}')};
const el=id=>document.getElementById(id);
const currentStock=id=>{const saved=JSON.parse(localStorage.getItem('cool-inventory')||'null');const p=products.find(x=>x.id===id);return saved&&saved[id]!==undefined?Number(saved[id]):Number(p?.stock||0)};
function saveCart(){localStorage.setItem('cool-cart',JSON.stringify(state.cart));renderCart()}
function categories(){return ['Todos',...new Set(products.map(p=>p.category))]}
function renderCategories(){el('categoryBar').innerHTML=categories().map(c=>`<button class="${state.category===c?'active':''}" data-category="${c}">${c}</button>`).join('');el('categoryBar').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;renderCategories();renderProducts()})}
function renderProducts(){const q=state.query.toLowerCase(),list=products.filter(p=>(state.category==='Todos'||p.category===state.category)&&(!q||`${p.name} ${p.category} ${p.description}`.toLowerCase().includes(q)));el('resultCount').textContent=`${list.length} productos`;el('productGrid').innerHTML=list.map(p=>{const available=currentStock(p.id);return `<article class="product-card"><div class="photo"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="stock">${available>0?`${available} disponibles`:'Agotado'}</span></div><div class="product-info"><small>${p.category}</small><h3>${p.name}</h3><p>${p.description}</p><div class="product-bottom"><strong>${money(p.price)}</strong><button class="add-button" data-id="${p.id}" ${available<1?'disabled':''}>+ Agregar</button></div></div></article>`}).join('')||'<p class="empty">No encontramos productos con esa búsqueda.</p>';el('productGrid').querySelectorAll('.add-button').forEach(b=>b.onclick=()=>addToCart(b.dataset.id))}
function addToCart(id){const p=products.find(x=>x.id===id),available=currentStock(id);if(!p||available<1)return;state.cart[id]=Math.min((state.cart[id]||0)+1,available);saveCart();showToast(`${p.name} agregado`)}
function changeQty(id,delta){state.cart[id]=Math.max(0,Math.min((state.cart[id]||0)+delta,currentStock(id)));if(!state.cart[id])delete state.cart[id];saveCart()}
function cartTotal(){return Object.entries(state.cart).reduce((sum,[id,q])=>sum+(products.find(p=>p.id===id)?.price||0)*q,0)}
function renderCart(){const entries=Object.entries(state.cart);el('cartCount').textContent=entries.reduce((s,[,q])=>s+q,0);el('cartItems').innerHTML=entries.length?entries.map(([id,q])=>{const p=products.find(x=>x.id===id);return `<article class="cart-item"><img src="${p.image}" alt=""><div><h4>${p.name}</h4><small>${money(p.price*q)}</small></div><div class="qty"><button data-id="${id}" data-delta="-1">−</button><b>${q}</b><button data-id="${id}" data-delta="1">+</button></div></article>`}).join(''):'<div class="empty">Tu carrito está vacío.<br>Agrega productos para comenzar.</div>';el('cartSubtotal').textContent=money(cartTotal());el('cartItems').querySelectorAll('.qty button').forEach(b=>b.onclick=()=>changeQty(b.dataset.id,Number(b.dataset.delta)))}
function toggleCart(open){el('cartDrawer').classList.toggle('open',open);el('overlay').classList.toggle('show',open);el('cartDrawer').setAttribute('aria-hidden',String(!open))}
function showToast(message){el('toast').textContent=message;el('toast').classList.add('show');setTimeout(()=>el('toast').classList.remove('show'),2200)}
function paymentText(value){return value==='Tarjeta'?'El pago con tarjeta será procesado mediante un enlace seguro; nunca solicitamos datos de tarjeta por WhatsApp.':value==='Contra entrega'?'Confirmaremos cobertura, entrega y monto antes de despachar.':value==='WhatsApp'?'El pedido será abierto en WhatsApp para confirmar disponibilidad y entrega.':'Recibirás los datos bancarios y la confirmación del pedido por WhatsApp.'}
function createOrder(form){const data=Object.fromEntries(new FormData(form));const items=Object.entries(state.cart).map(([id,q])=>{const p=products.find(x=>x.id===id);return {id,name:p.name,price:p.price,qty:q}});const order={id:'CS-'+Date.now().toString().slice(-8),date:new Date().toISOString(),status:'Nuevo',source:'Tienda online',customer:{name:data.name,phone:data.phone,address:data.address,city:data.city},delivery:data.delivery,payment:data.payment,items,total:cartTotal()};const orders=JSON.parse(localStorage.getItem('cool-orders')||'[]');orders.unshift(order);localStorage.setItem('cool-orders',JSON.stringify(orders));window.dispatchEvent(new StorageEvent('storage',{key:'cool-orders'}));return order}
function sendOrder(order){const items=order.items.map(x=>`• ${x.qty} x ${x.name} — ${money(x.price*x.qty)}`).join('\n');const message=`*NUEVO PEDIDO ${order.id}*\n\n${items}\n\n*Total:* ${money(order.total)}\n*Cliente:* ${order.customer.name}\n*Teléfono:* ${order.customer.phone}\n*Entrega:* ${order.delivery}\n*Dirección:* ${order.customer.address}, ${order.customer.city}\n*Pago:* ${order.payment}`;window.open(`https://wa.me/18095095225?text=${encodeURIComponent(message)}`,'_blank')}
el('searchInput').oninput=e=>{state.query=e.target.value;renderProducts()};el('cartButton').onclick=()=>toggleCart(true);el('closeCart').onclick=()=>toggleCart(false);el('overlay').onclick=()=>toggleCart(false);el('checkoutButton').onclick=()=>{if(!Object.keys(state.cart).length)return showToast('Tu carrito está vacío');toggleCart(false);el('checkoutDialog').showModal()};el('closeCheckout').onclick=()=>el('checkoutDialog').close();document.querySelectorAll('[name="payment"]').forEach(r=>r.onchange=()=>el('paymentNote').textContent=paymentText(r.value));el('checkoutForm').onsubmit=e=>{e.preventDefault();const order=createOrder(e.currentTarget);sendOrder(order);state.cart={};saveCart();e.currentTarget.reset();el('checkoutDialog').close();showToast(`Pedido ${order.id} creado`)};renderCategories();renderProducts();renderCart();
